apiVersion: 1
prune: true

datasources:
  - name: Zabbix FastAPI
    uid: zabbix-fastapi
    type: yesoreyeram-infinity-datasource
    access: proxy
    orgId: 1
    isDefault: false
    editable: false
    url: http://127.0.0.1:$APP_PORT
    jsonData:
      auth_method: bearerToken
      allowedHosts:
        - http://127.0.0.1:$APP_PORT
      allowDangerousHTTPMethods: false
      timeoutInSeconds: 10
    secureJsonData:
      bearerToken: $GRAFANA_API_TOKEN
